### YamlMime:ManagedReference
items:
- uid: Flex.Smoothlake.FlexLib.ALEComposite.ALEConfigurationRemovedEventHandler
  commentId: T:Flex.Smoothlake.FlexLib.ALEComposite.ALEConfigurationRemovedEventHandler
  id: ALEComposite.ALEConfigurationRemovedEventHandler
  parent: Flex.Smoothlake.FlexLib
  children: []
  langs:
  - csharp
  - vb
  name: ALEComposite.ALEConfigurationRemovedEventHandler
  nameWithType: ALEComposite.ALEConfigurationRemovedEventHandler
  fullName: Flex.Smoothlake.FlexLib.ALEComposite.ALEConfigurationRemovedEventHandler
  type: Delegate
  source:
    id: ALEConfigurationRemovedEventHandler
    path: C:\Users\chris\OneDrive\Documents\github\FlexLib_API_v4.1.5.39794\FlexLib\ALEComposite.cs
    startLine: 958
  assemblies:
  - FlexLib
  namespace: Flex.Smoothlake.FlexLib
  syntax:
    content: public delegate void ALEComposite.ALEConfigurationRemovedEventHandler(ALEConfiguration configuration)
    parameters:
    - id: configuration
      type: Flex.Smoothlake.FlexLib.ALEConfiguration
    content.vb: Public Delegate Sub ALEComposite.ALEConfigurationRemovedEventHandler(configuration As ALEConfiguration)
references:
- uid: Flex.Smoothlake.FlexLib
  commentId: N:Flex.Smoothlake.FlexLib
  href: Flex.html
  name: Flex.Smoothlake.FlexLib
  nameWithType: Flex.Smoothlake.FlexLib
  fullName: Flex.Smoothlake.FlexLib
  spec.csharp:
  - uid: Flex
    name: Flex
    href: Flex.html
  - name: .
  - uid: Flex.Smoothlake
    name: Smoothlake
    href: Flex.Smoothlake.html
  - name: .
  - uid: Flex.Smoothlake.FlexLib
    name: FlexLib
    href: Flex.Smoothlake.FlexLib.html
  spec.vb:
  - uid: Flex
    name: Flex
    href: Flex.html
  - name: .
  - uid: Flex.Smoothlake
    name: Smoothlake
    href: Flex.Smoothlake.html
  - name: .
  - uid: Flex.Smoothlake.FlexLib
    name: FlexLib
    href: Flex.Smoothlake.FlexLib.html
- uid: Flex.Smoothlake.FlexLib.ALEConfiguration
  commentId: T:Flex.Smoothlake.FlexLib.ALEConfiguration
  parent: Flex.Smoothlake.FlexLib
  href: Flex.Smoothlake.FlexLib.ALEConfiguration.html
  name: ALEConfiguration
  nameWithType: ALEConfiguration
  fullName: Flex.Smoothlake.FlexLib.ALEConfiguration
