### YamlMime:ManagedReference
items:
- uid: Flex.Smoothlake.FlexLib.Radio.TxBandSettingsAddedEventHandler
  commentId: T:Flex.Smoothlake.FlexLib.Radio.TxBandSettingsAddedEventHandler
  id: Radio.TxBandSettingsAddedEventHandler
  parent: Flex.Smoothlake.FlexLib
  children: []
  langs:
  - csharp
  - vb
  name: Radio.TxBandSettingsAddedEventHandler
  nameWithType: Radio.TxBandSettingsAddedEventHandler
  fullName: Flex.Smoothlake.FlexLib.Radio.TxBandSettingsAddedEventHandler
  type: Delegate
  source:
    id: TxBandSettingsAddedEventHandler
    path: C:\Users\chris\OneDrive\Documents\github\FlexLib_API_v4.1.5.39794\FlexLib\Radio.cs
    startLine: 4632
  assemblies:
  - FlexLib
  namespace: Flex.Smoothlake.FlexLib
  summary: Delegate event handler for the TxBandSettingsAddedEventHandler event
  example: []
  syntax:
    content: public delegate void Radio.TxBandSettingsAddedEventHandler(TxBandSettings txBandSettings)
    parameters:
    - id: txBandSettings
      type: Flex.Smoothlake.FlexLib.TxBandSettings
      description: ''
    content.vb: Public Delegate Sub Radio.TxBandSettingsAddedEventHandler(txBandSettings As TxBandSettings)
references:
- uid: Flex.Smoothlake.FlexLib
  commentId: N:Flex.Smoothlake.FlexLib
  href: Flex.html
  name: Flex.Smoothlake.FlexLib
  nameWithType: Flex.Smoothlake.FlexLib
  fullName: Flex.Smoothlake.FlexLib
  spec.csharp:
  - uid: Flex
    name: Flex
    href: Flex.html
  - name: .
  - uid: Flex.Smoothlake
    name: Smoothlake
    href: Flex.Smoothlake.html
  - name: .
  - uid: Flex.Smoothlake.FlexLib
    name: FlexLib
    href: Flex.Smoothlake.FlexLib.html
  spec.vb:
  - uid: Flex
    name: Flex
    href: Flex.html
  - name: .
  - uid: Flex.Smoothlake
    name: Smoothlake
    href: Flex.Smoothlake.html
  - name: .
  - uid: Flex.Smoothlake.FlexLib
    name: FlexLib
    href: Flex.Smoothlake.FlexLib.html
- uid: Flex.Smoothlake.FlexLib.TxBandSettings
  commentId: T:Flex.Smoothlake.FlexLib.TxBandSettings
  parent: Flex.Smoothlake.FlexLib
  href: Flex.Smoothlake.FlexLib.TxBandSettings.html
  name: TxBandSettings
  nameWithType: TxBandSettings
  fullName: Flex.Smoothlake.FlexLib.TxBandSettings
