### YamlMime:ManagedReference
items:
- uid: Flex.Smoothlake.FlexLib.Radio.TxBandSettingsRemovedEventHandler
  commentId: T:Flex.Smoothlake.FlexLib.Radio.TxBandSettingsRemovedEventHandler
  id: Radio.TxBandSettingsRemovedEventHandler
  parent: Flex.Smoothlake.FlexLib
  children: []
  langs:
  - csharp
  - vb
  name: Radio.TxBandSettingsRemovedEventHandler
  nameWithType: Radio.TxBandSettingsRemovedEventHandler
  fullName: Flex.Smoothlake.FlexLib.Radio.TxBandSettingsRemovedEventHandler
  type: Delegate
  source:
    id: TxBandSettingsRemovedEventHandler
    path: C:\Users\chris\OneDrive\Documents\github\FlexLib_API_v4.1.5.39794\FlexLib\Radio.cs
    startLine: 4648
  assemblies:
  - FlexLib
  namespace: Flex.Smoothlake.FlexLib
  summary: Delegate event handler for the TxBandSettingsRemovedEventHandler event
  example: []
  syntax:
    content: public delegate void Radio.TxBandSettingsRemovedEventHandler(TxBandSettings txBandSettings)
    parameters:
    - id: txBandSettings
      type: Flex.Smoothlake.FlexLib.TxBandSettings
      description: ''
    content.vb: Public Delegate Sub Radio.TxBandSettingsRemovedEventHandler(txBandSettings As TxBandSettings)
references:
- uid: Flex.Smoothlake.FlexLib
  commentId: N:Flex.Smoothlake.FlexLib
  href: Flex.html
  name: Flex.Smoothlake.FlexLib
  nameWithType: Flex.Smoothlake.FlexLib
  fullName: Flex.Smoothlake.FlexLib
  spec.csharp:
  - uid: Flex
    name: Flex
    href: Flex.html
  - name: .
  - uid: Flex.Smoothlake
    name: Smoothlake
    href: Flex.Smoothlake.html
  - name: .
  - uid: Flex.Smoothlake.FlexLib
    name: FlexLib
    href: Flex.Smoothlake.FlexLib.html
  spec.vb:
  - uid: Flex
    name: Flex
    href: Flex.html
  - name: .
  - uid: Flex.Smoothlake
    name: Smoothlake
    href: Flex.Smoothlake.html
  - name: .
  - uid: Flex.Smoothlake.FlexLib
    name: FlexLib
    href: Flex.Smoothlake.FlexLib.html
- uid: Flex.Smoothlake.FlexLib.TxBandSettings
  commentId: T:Flex.Smoothlake.FlexLib.TxBandSettings
  parent: Flex.Smoothlake.FlexLib
  href: Flex.Smoothlake.FlexLib.TxBandSettings.html
  name: TxBandSettings
  nameWithType: TxBandSettings
  fullName: Flex.Smoothlake.FlexLib.TxBandSettings
