### YamlMime:ManagedReference
items:
- uid: Flex.Util.DisplayConfig
  commentId: T:Flex.Util.DisplayConfig
  id: DisplayConfig
  parent: Flex.Util
  children:
  - Flex.Util.DisplayConfig.GetModes(Flex.Util.DisplayConfig.PathFlags)
  - Flex.Util.DisplayConfig.GetPaths(Flex.Util.DisplayConfig.PathFlags)
  - Flex.Util.DisplayConfig.SetPaths(System.Collections.Generic.IEnumerable{Flex.Util.DisplayConfigPath})
  langs:
  - csharp
  - vb
  name: DisplayConfig
  nameWithType: DisplayConfig
  fullName: Flex.Util.DisplayConfig
  type: Class
  source:
    id: DisplayConfig
    path: C:\Users\chris\OneDrive\Documents\github\FlexLib_API_v4.1.5.39794\Util\Display.cs
    startLine: 599
  assemblies:
  - Util
  namespace: Flex.Util
  syntax:
    content: public static class DisplayConfig
    content.vb: Public Module DisplayConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Flex.Util.DisplayConfig.GetPaths(Flex.Util.DisplayConfig.PathFlags)
  commentId: M:Flex.Util.DisplayConfig.GetPaths(Flex.Util.DisplayConfig.PathFlags)
  id: GetPaths(Flex.Util.DisplayConfig.PathFlags)
  parent: Flex.Util.DisplayConfig
  langs:
  - csharp
  - vb
  name: GetPaths(PathFlags)
  nameWithType: DisplayConfig.GetPaths(DisplayConfig.PathFlags)
  fullName: Flex.Util.DisplayConfig.GetPaths(Flex.Util.DisplayConfig.PathFlags)
  type: Method
  source:
    id: GetPaths
    path: C:\Users\chris\OneDrive\Documents\github\FlexLib_API_v4.1.5.39794\Util\Display.cs
    startLine: 711
  assemblies:
  - Util
  namespace: Flex.Util
  syntax:
    content: public static IEnumerable<DisplayConfigPath> GetPaths(DisplayConfig.PathFlags pathFlags)
    parameters:
    - id: pathFlags
      type: Flex.Util.DisplayConfig.PathFlags
    return:
      type: System.Collections.Generic.IEnumerable{Flex.Util.DisplayConfigPath}
    content.vb: Public Shared Function GetPaths(pathFlags As DisplayConfig.PathFlags) As IEnumerable(Of DisplayConfigPath)
  overload: Flex.Util.DisplayConfig.GetPaths*
- uid: Flex.Util.DisplayConfig.SetPaths(System.Collections.Generic.IEnumerable{Flex.Util.DisplayConfigPath})
  commentId: M:Flex.Util.DisplayConfig.SetPaths(System.Collections.Generic.IEnumerable{Flex.Util.DisplayConfigPath})
  id: SetPaths(System.Collections.Generic.IEnumerable{Flex.Util.DisplayConfigPath})
  parent: Flex.Util.DisplayConfig
  langs:
  - csharp
  - vb
  name: SetPaths(IEnumerable<DisplayConfigPath>)
  nameWithType: DisplayConfig.SetPaths(IEnumerable<DisplayConfigPath>)
  fullName: Flex.Util.DisplayConfig.SetPaths(System.Collections.Generic.IEnumerable<Flex.Util.DisplayConfigPath>)
  type: Method
  source:
    id: SetPaths
    path: C:\Users\chris\OneDrive\Documents\github\FlexLib_API_v4.1.5.39794\Util\Display.cs
    startLine: 718
  assemblies:
  - Util
  namespace: Flex.Util
  syntax:
    content: public static void SetPaths(IEnumerable<DisplayConfigPath> paths)
    parameters:
    - id: paths
      type: System.Collections.Generic.IEnumerable{Flex.Util.DisplayConfigPath}
    content.vb: Public Shared Sub SetPaths(paths As IEnumerable(Of DisplayConfigPath))
  overload: Flex.Util.DisplayConfig.SetPaths*
  nameWithType.vb: DisplayConfig.SetPaths(IEnumerable(Of DisplayConfigPath))
  fullName.vb: Flex.Util.DisplayConfig.SetPaths(System.Collections.Generic.IEnumerable(Of Flex.Util.DisplayConfigPath))
  name.vb: SetPaths(IEnumerable(Of DisplayConfigPath))
- uid: Flex.Util.DisplayConfig.GetModes(Flex.Util.DisplayConfig.PathFlags)
  commentId: M:Flex.Util.DisplayConfig.GetModes(Flex.Util.DisplayConfig.PathFlags)
  id: GetModes(Flex.Util.DisplayConfig.PathFlags)
  parent: Flex.Util.DisplayConfig
  langs:
  - csharp
  - vb
  name: GetModes(PathFlags)
  nameWithType: DisplayConfig.GetModes(DisplayConfig.PathFlags)
  fullName: Flex.Util.DisplayConfig.GetModes(Flex.Util.DisplayConfig.PathFlags)
  type: Method
  source:
    id: GetModes
    path: C:\Users\chris\OneDrive\Documents\github\FlexLib_API_v4.1.5.39794\Util\Display.cs
    startLine: 731
  assemblies:
  - Util
  namespace: Flex.Util
  syntax:
    content: public static IEnumerable<DisplayConfigMode> GetModes(DisplayConfig.PathFlags pathFlags)
    parameters:
    - id: pathFlags
      type: Flex.Util.DisplayConfig.PathFlags
    return:
      type: System.Collections.Generic.IEnumerable{Flex.Util.DisplayConfigMode}
    content.vb: Public Shared Function GetModes(pathFlags As DisplayConfig.PathFlags) As IEnumerable(Of DisplayConfigMode)
  overload: Flex.Util.DisplayConfig.GetModes*
references:
- uid: Flex.Util
  commentId: N:Flex.Util
  href: Flex.html
  name: Flex.Util
  nameWithType: Flex.Util
  fullName: Flex.Util
  spec.csharp:
  - uid: Flex
    name: Flex
    href: Flex.html
  - name: .
  - uid: Flex.Util
    name: Util
    href: Flex.Util.html
  spec.vb:
  - uid: Flex
    name: Flex
    href: Flex.html
  - name: .
  - uid: Flex.Util
    name: Util
    href: Flex.Util.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Flex.Util.DisplayConfig.GetPaths*
  commentId: Overload:Flex.Util.DisplayConfig.GetPaths
  href: Flex.Util.DisplayConfig.html#Flex_Util_DisplayConfig_GetPaths_Flex_Util_DisplayConfig_PathFlags_
  name: GetPaths
  nameWithType: DisplayConfig.GetPaths
  fullName: Flex.Util.DisplayConfig.GetPaths
- uid: Flex.Util.DisplayConfig.PathFlags
  commentId: T:Flex.Util.DisplayConfig.PathFlags
  parent: Flex.Util
  href: Flex.Util.DisplayConfig.html
  name: DisplayConfig.PathFlags
  nameWithType: DisplayConfig.PathFlags
  fullName: Flex.Util.DisplayConfig.PathFlags
  spec.csharp:
  - uid: Flex.Util.DisplayConfig
    name: DisplayConfig
    href: Flex.Util.DisplayConfig.html
  - name: .
  - uid: Flex.Util.DisplayConfig.PathFlags
    name: PathFlags
    href: Flex.Util.DisplayConfig.PathFlags.html
  spec.vb:
  - uid: Flex.Util.DisplayConfig
    name: DisplayConfig
    href: Flex.Util.DisplayConfig.html
  - name: .
  - uid: Flex.Util.DisplayConfig.PathFlags
    name: PathFlags
    href: Flex.Util.DisplayConfig.PathFlags.html
- uid: System.Collections.Generic.IEnumerable{Flex.Util.DisplayConfigPath}
  commentId: T:System.Collections.Generic.IEnumerable{Flex.Util.DisplayConfigPath}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<DisplayConfigPath>
  nameWithType: IEnumerable<DisplayConfigPath>
  fullName: System.Collections.Generic.IEnumerable<Flex.Util.DisplayConfigPath>
  nameWithType.vb: IEnumerable(Of DisplayConfigPath)
  fullName.vb: System.Collections.Generic.IEnumerable(Of Flex.Util.DisplayConfigPath)
  name.vb: IEnumerable(Of DisplayConfigPath)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: Flex.Util.DisplayConfigPath
    name: DisplayConfigPath
    href: Flex.Util.DisplayConfigPath.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: Flex.Util.DisplayConfigPath
    name: DisplayConfigPath
    href: Flex.Util.DisplayConfigPath.html
  - name: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Flex.Util.DisplayConfig.SetPaths*
  commentId: Overload:Flex.Util.DisplayConfig.SetPaths
  href: Flex.Util.DisplayConfig.html#Flex_Util_DisplayConfig_SetPaths_System_Collections_Generic_IEnumerable_Flex_Util_DisplayConfigPath__
  name: SetPaths
  nameWithType: DisplayConfig.SetPaths
  fullName: Flex.Util.DisplayConfig.SetPaths
- uid: Flex.Util.DisplayConfig.GetModes*
  commentId: Overload:Flex.Util.DisplayConfig.GetModes
  href: Flex.Util.DisplayConfig.html#Flex_Util_DisplayConfig_GetModes_Flex_Util_DisplayConfig_PathFlags_
  name: GetModes
  nameWithType: DisplayConfig.GetModes
  fullName: Flex.Util.DisplayConfig.GetModes
- uid: System.Collections.Generic.IEnumerable{Flex.Util.DisplayConfigMode}
  commentId: T:System.Collections.Generic.IEnumerable{Flex.Util.DisplayConfigMode}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<DisplayConfigMode>
  nameWithType: IEnumerable<DisplayConfigMode>
  fullName: System.Collections.Generic.IEnumerable<Flex.Util.DisplayConfigMode>
  nameWithType.vb: IEnumerable(Of DisplayConfigMode)
  fullName.vb: System.Collections.Generic.IEnumerable(Of Flex.Util.DisplayConfigMode)
  name.vb: IEnumerable(Of DisplayConfigMode)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: Flex.Util.DisplayConfigMode
    name: DisplayConfigMode
    href: Flex.Util.DisplayConfigMode.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: Flex.Util.DisplayConfigMode
    name: DisplayConfigMode
    href: Flex.Util.DisplayConfigMode.html
  - name: )
